apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
- llm-ops-backend-svc.yaml
- llm-ops-frontend-svc.yaml
- llm-ops-config.yaml
- llm-ops-kubeconfig.yaml
images:
- name: image.ppinfra.com/llm-ops/backend
  newTag: 0.7.9
- name: image.ppinfra.com/llm-ops/frontend
  newTag: 0.7.9

